### ISSUE TITLE
tvclient - Project link for module is wrong

### ISSUE THREAD

**Issue by wsmelton** [potatoqualitee/tvbot#63]
Seems the link used in the psd1 for the ProjectUri is not resolving to the folder in the project. 

https://github.com/potatoqualitee/twitch/blob/dc1336393d7f5bba2d14d7f59564ea5f06b67c49/tvclient/tvclient.psd1#L96-L97

Instead of using trying to link to the folder which would require a URL like `https://github.com/potatoqualitee/twitch/blob/main/tvclient` you might link to the root project instead `https://github.com/potatoqualitee/twitch` (have seen other projects do this when they are storing the modules in the same repo).

**Comment by potatoqualitee** [comment]
oh! you are right, thank you, will update

**Comment by potatoqualitee** [comment]
done!
