### ISSUE TITLE
some code

### ISSUE THREAD

**Issue by potatoqualitee** [potatoqualitee/tvbot#8]
Invoke-RestMethod -Uri "https://api.twitch.tv/kraken/user" -Headers @{
    "Accept"        = "application/vnd.twitchtv.v5+json"
    "Client-ID"             = "uo6dggojyb8d6soh92zknwmi5ej1q2"
    "Authorization" = "OAuth $token"
} -Method Get

**Comment by potatoqualitee** [comment]
Use upper case name

badge-info=;badges=;client-nonce=b5c3bc0e7325408ef3cbec815ec905af;color=#8A2BE2;display-name=BWMerlin;emotes=;flags=;id=f6197fef-a088-4ae9-8dd6-0294d832bd66
;mod=0;room-id=403789625;subscriber=0;tmi-sent-ts=1608600475127;turbo=0;user-id=45270829;user-type= :bwmerlin!bwmerlin@bwmerlin.tmi.twitch.tv PRIVMSG

**Comment by potatoqualitee** [comment]
need to fix if there's a login failure, dont just die

**Comment by potatoqualitee** [comment]
cache when they enter the room and use a runspace

**Comment by Windos** [comment]
> cache when they enter the room and use a runspace

Alternative, occasionally get list of current viewers and cache anyone not already in the cache. If they talk before being cached either do JIT avatar grab... or default image.

**Comment by potatoqualitee** [comment]
auto emote conversion

https://discuss.dev.twitch.tv/t/grabbing-chat-messages-with-new-twitch-api/27555

**Comment by potatoqualitee** [comment]
create github actions to test for pi compat

**Comment by potatoqualitee** [comment]
used code!
